// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service_simple_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x90\x04\n" +
	"\x11SimpleBankService\x12\xae\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"q\x92AT\n" +
	"\x04user\x12\x11Create a new user\x1a9This is the endpoint that allows you to create a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\xa6\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"i\x92AL\n" +
	"\x04user\x12\rUpdate a user\x1a5This is the endpoint that allows you to update a user\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/update_user\x12\xa0\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"f\x92AJ\n" +
	"\x04user\x12\fLogin a user\x1a4This is the endpoint that allows you to login a user\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_userB\x9f\x01\x92Ag\x12e\n" +
	"\x0fSimple Bank API\"M\n" +
	"\x0eGo Systems Lab\x12!https://github.com/go-systems-lab\x1a\x18go-systems-lab@gmail.com2\x031.1Z3github.com/go-systems-lab/go-backend-masterclass/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),  // 1: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),   // 2: pb.LoginUserRequest
	(*CreateUserResponse)(nil), // 3: pb.CreateUserResponse
	(*UpdateUserResponse)(nil), // 4: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),  // 5: pb.LoginUserResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBankService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SimpleBankService.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.SimpleBankService.LoginUser:input_type -> pb.LoginUserRequest
	3, // 3: pb.SimpleBankService.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.SimpleBankService.UpdateUser:output_type -> pb.UpdateUserResponse
	5, // 5: pb.SimpleBankService.LoginUser:output_type -> pb.LoginUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
